clear all

* Load map of districts (aggregated up to consistent master name spatial units)
cd "$temp_dir" //set directory to temp dir such that generated data sets are saved there
		
shp2dta using "$data_dir/England_and_Wales/district_shapefiles/EW1851_regdistricts", data(districts) coor(distcoor) genid(id) genc(c) replace

* Recover ids created by shp2dta and map to district names
	use G_NAME NATION id using "$temp_dir/districts", clear
		rename G_NAME regdist
		
gen district=""	

replace district="ABERAYRON" if regdist=="ABERAERON"
replace district="ABERGAVENNY AND PONTYPOOL" if regdist=="ABERGAVENNY"
replace district="ABERYSTWITH" if regdist=="ABERYSTWITH"
replace district="OXFORD" if regdist=="ABINGDON"
replace district="ALCESTER" if regdist=="ALCESTER"
replace district="SALISBURY" if regdist=="ALDERBURY"
replace district="ALNWICK" if regdist=="ALNWICK"
replace district="ALRESFORD" if regdist=="ALRESFORD"
replace district="ALSTON" if regdist=="ALSTON WITH GARRIGILL"
replace district="FARNHAM" if regdist=="ALTON"
replace district="ALTRINCHAM" if regdist=="ALTRINCHAM"
replace district="ALVERSTOKE" if regdist=="ALVERSTOKE"
replace district="AMERSHAM AND ETON" if regdist=="AMERSHAM"
replace district="AMESBURY" if regdist=="AMESBURY"
replace district="BERKHAMPSTEAD" if regdist=="AMPTHILL"
replace district="ANDOVER" if regdist=="ANDOVER"
replace district="BANGOR AND ANGLESEA" if regdist=="ANGLESEY"
replace district="WOLSTANTON ETC" if regdist=="ASHBOURNE"
replace district="ASHBY-DE-LA-ZOUCH" if regdist=="ASHBY DE LA ZOUCH"
replace district="ASHTON-UNDER-LYME" if regdist=="ASHTON UNDER LYNE"
replace district="ASKRIGG" if regdist=="ASKRIGG"
replace district="ASTON" if regdist=="ASTON"
replace district="ATCHAM AND SHREWSBURY" if regdist=="ATCHAM"
replace district="ATHERSTONE" if regdist=="ATHERSTONE"
replace district="AUCKLAND" if regdist=="AUCKLAND"
replace district="BRIDGEWATER ETC" if regdist=="AXBRIDGE"
replace district="BEAMINSTER ETC" if regdist=="AXMINSTER"
replace district="WYCOMBE AYLESBURY THAME" if regdist=="AYLESBURY"
replace district="AYLSHAM" if regdist=="AYLSHAM"
replace district="BAKEWELL" if regdist=="BAKEWELL"
replace district="BALA" if regdist=="BALA"
replace district="BANBURY" if regdist=="BANBURY"
replace district="BANGOR AND ANGLESEA" if regdist=="BANGOR AND BEAUMARIS"
replace district="BARNET AND EDMONTON" if regdist=="BARNET"
replace district="BARNSLEY" if regdist=="BARNSLEY"
replace district="BARNSTAPLE" if regdist=="BARNSTAPLE"
replace district="LEICESTER" if regdist=="BARROW UPON SOAR"
replace district="BARTON-UPON-IRWELL" if regdist=="BARTON UPON IRWELL"
replace district="NOTTINGHAM ETC" if regdist=="BASFORD"
replace district="READING" if regdist=="BASINGSTOKE"
replace district="BATH ETC" if regdist=="BATH"
replace district="BATTLE" if regdist=="BATTLE"
replace district="BEAMINSTER ETC" if regdist=="BEAMINSTER"
replace district="GREATER LEEDS" if regdist=="BEDALE"
replace district="BEDFORD" if regdist=="BEDFORD"
replace district="BRISTOL" if regdist=="BEDMINSTER"
replace district="BELFORD" if regdist=="BELFORD"
replace district="BELLINGHAM" if regdist=="BELLINGHAM"
replace district="DERBY ETC" if regdist=="BELPER"
replace district="BERKHAMPSTEAD" if regdist=="BERKHAMPSTEAD"
replace district="ST OLAVE SOUTHWARK" if regdist=="BERMONDSEY"
replace district="BERWICK" if regdist=="BERWICK"
replace district="BETHNAL GREEN" if regdist=="BETHNAL GREEN"
replace district="BEVERLEY" if regdist=="BEVERLEY"
replace district="BICESTER" if regdist=="BICESTER"
replace district="BIDEFORD ETC" if regdist=="BIDEFORD"
replace district="BIGGLESWADE" if regdist=="BIGGLESWADE"
replace district="BILLERICAY AND ROCHFORD" if regdist=="BILLERICAY"
replace district="LEICESTER" if regdist=="BILLESDON"
replace district="BINGHAM" if regdist=="BINGHAM"
replace district="BIRMINGHAM" if regdist=="BIRMINGHAM"
replace district="BISHOP STORTFORD" if regdist=="BISHOPS STORTFORD"
replace district="LEICESTER" if regdist=="BLABY"
replace district="BLACKBURN" if regdist=="BLACKBURN"
replace district="BLANDFORD AND WIMBORNE" if regdist=="BLANDFORD"
replace district="BLEAN" if regdist=="BLEAN"
replace district="BLOFIELD" if regdist=="BLOFIELD"
replace district="BLYTHING" if regdist=="BLYTHING"
replace district="BODMIN AND ST COLUMB" if regdist=="BODMIN"
replace district="BOLTON" if regdist=="BOLTON"
replace district="BOOTLE" if regdist=="BOOTLE"
replace district="IPSWICH" if regdist=="BOSMERE AND CLAYDON"
replace district="BOSTON ETC" if regdist=="BOSTON"
replace district="BOURN AND SPALDING" if regdist=="BOURNE"
replace district="BRACKLEY" if regdist=="BRACKLEY"
replace district="READING" if regdist=="BRADFIELD"
replace district="BRADFORD ETC" if regdist=="BRADFORD"
replace district="BATH ETC" if regdist=="BRADFORD ON AVON"
replace district="MALDON ETC" if regdist=="BRAINTREE"
replace district="BRAMPTON" if regdist=="BRAMPTON"
replace district="BRECKNOCK" if regdist=="BRECKNOCK"
replace district="UXBRIDGE AND BRENTFORD" if regdist=="BRENTFORD"
replace district="BRIDGE" if regdist=="BRIDGE"
replace district="SWANSEA ETC" if regdist=="BRIDGEND AND COWBRIDGE"
replace district="BRIDGNORTH" if regdist=="BRIDGNORTH"
replace district="BRIDGEWATER ETC" if regdist=="BRIDGWATER"
replace district="BRIDLINGTON" if regdist=="BRIDLINGTON"
replace district="BEAMINSTER ETC" if regdist=="BRIDPORT"
replace district="BRIGHTON" if regdist=="BRIGHTON"
replace district="BRISTOL" if regdist=="BRISTOL"
replace district="BRIXWORTH" if regdist=="BRIXWORTH"
replace district="GREENWICH" if regdist=="BROMLEY"
replace district="BROMSGROVE" if regdist=="BROMSGROVE"
replace district="WORCESTER ETC" if regdist=="BROMYARD"
replace district="BUCKINGHAM" if regdist=="BUCKINGHAM"
replace district="LLANDOVERY ETC" if regdist=="BUILTH"
replace district="BRADFORD ETC" if regdist=="BURNLEY"
replace district="BURTON-UPON-TRENT" if regdist=="BURTON UPON TRENT"
replace district="BURY" if regdist=="BURY"
replace district="BURY ST EDMUNDS" if regdist=="BURY ST EDMUNDS"
replace district="GRIMSBY" if regdist=="CAISTOR"
replace district="CHIPPENHAM AND CALNE" if regdist=="CALNE"
replace district="CAMBERWELL" if regdist=="CAMBERWELL"
replace district="CAMBRIDGE" if regdist=="CAMBRIDGE"
replace district="CAMELFORD" if regdist=="CAMELFORD"
replace district="CANTERBURY" if regdist=="CANTERBURY"
replace district="CARDIFF AND NEWPORT" if regdist=="CARDIFF"
replace district="CARDIGAN" if regdist=="CARDIGAN"
replace district="CARLISLE" if regdist=="CARLISLE"
replace district="LLANELLY AND CARMARTHEN" if regdist=="CARMARTHEN"
replace district="CARNARVON" if regdist=="CARNARVON"
replace district="CASTLE WARD" if regdist=="CASTLE WARD"
replace district="CATHERINGTON" if regdist=="CATHERINGTON"
replace district="CAXTON" if regdist=="CAXTON"
replace district="CHAPEL-EN-LE-FRITH" if regdist=="CHAPEL EN LE FRITH"
replace district="BEAMINSTER ETC" if regdist=="CHARD"
replace district="STOKE ETC" if regdist=="CHEADLE"
replace district="CHELMSFORD" if regdist=="CHELMSFORD"
replace district="CHELSEA" if regdist=="CHELSEA"
replace district="CHELTENHAM" if regdist=="CHELTENHAM"
replace district="CHEPSTOW" if regdist=="CHEPSTOW"
replace district="WINDSOR" if regdist=="CHERTSEY"
replace district="DURHAM" if regdist=="CHESTER LE STREET"
replace district="CHESTERFIELD" if regdist=="CHESTERFIELD"
replace district="CHESTERTON" if regdist=="CHESTERTON"
replace district="CHICHESTER ETC" if regdist=="CHICHESTER"
replace district="CHIPPENHAM AND CALNE" if regdist=="CHIPPENHAM"
replace district="CHIPPING NORTON" if regdist=="CHIPPING NORTON"
replace district="CHIPPING SODBURY" if regdist=="CHIPPING SODBURY"
replace district="CHORLEY" if regdist=="CHORLEY"
replace district="CHORLTON" if regdist=="CHORLTON"
replace district="CHRISTCHURCH" if regdist=="CHRISTCHURCH"
replace district="CHURCH STRETTON" if regdist=="CHURCH STRETTON"
replace district="CRICKLADE ETC" if regdist=="CIRENCESTER"
replace district="LONDON CITY" if regdist=="CITY OF LONDON"
replace district="CLEOBURY-MORTIMER AND KIDDERMINSTER" if regdist=="CLEOBURY MORTIMER"
replace district="HOLBORN" if regdist=="CLERKENWELL"
replace district="BRISTOL" if regdist=="CLIFTON"
replace district="CLITHEROE" if regdist=="CLITHEROE"
replace district="CLUN" if regdist=="CLUN"
replace district="BATH ETC" if regdist=="CLUTTON"
replace district="COCKERMOUTH" if regdist=="COCKERMOUTH"
replace district="COLCHESTER" if regdist=="COLCHESTER"
replace district="WOLSTANTON ETC" if regdist=="CONGLETON"
replace district="CONWAY" if regdist=="CONWAY"
replace district="COOKHAM" if regdist=="COOKHAM"
replace district="CORWEN" if regdist=="CORWEN"
replace district="COSFORD" if regdist=="COSFORD"
replace district="COVENTRY ETC" if regdist=="COVENTRY"
replace district="CRANBROOK" if regdist=="CRANBROOK"
replace district="CREDITON" if regdist=="CREDITON"
replace district="ABERGAVENNY AND PONTYPOOL" if regdist=="CRICKHOWEL"
replace district="CRICKLADE ETC" if regdist=="CRICKLADE AND WOOTTON BASSETT"
replace district="CROYDON" if regdist=="CROYDON"
replace district="CHICHESTER ETC" if regdist=="CUCKFIELD"
replace district="DARLINGTON" if regdist=="DARLINGTON"
replace district="DARTFORD" if regdist=="DARTFORD"
replace district="DAVENTRY" if regdist=="DAVENTRY"
replace district="HOXNE AND DEPWADE" if regdist=="DEPWADE"
replace district="DERBY ETC" if regdist=="DERBY"
replace district="DEVIZES" if regdist=="DEVIZES"
replace district="DEWSBURY" if regdist=="DEWSBURY"
replace district="DOCKING" if regdist=="DOCKING"
replace district="DOLGELLY" if regdist=="DOLGELLY"
replace district="DONCASTER" if regdist=="DONCASTER"
replace district="DORCHESTER" if regdist=="DORCHESTER"
replace district="DORKING" if regdist=="DORKING"
replace district="DOVER" if regdist=="DOVER"
replace district="DOWNHAM" if regdist=="DOWNHAM"
replace district="DRIFFIELD" if regdist=="DRIFFIELD"
replace district="WORCESTER ETC" if regdist=="DROITWICH"
replace district="DROXFORD" if regdist=="DROXFORD"
replace district="DUDLEY" if regdist=="DUDLEY"
replace district="DUNMOW" if regdist=="DUNMOW"
replace district="DURHAM" if regdist=="DURHAM"
replace district="DURSLEY" if regdist=="DURSLEY"
replace district="EASINGTON" if regdist=="EASINGTON"
replace district="GREATER LEEDS" if regdist=="EASINGWOLD"
replace district="FLEGG" if regdist=="EAST AND WEST FLEGG"
replace district="EAST ASHFORD" if regdist=="EAST ASHFORD"
replace district="CHICHESTER ETC" if regdist=="EAST GRINSTEAD"
replace district="LONDON CITY" if regdist=="EAST LONDON"
replace district="THAKEHAM" if regdist=="EAST PRESTON"
replace district="EAST RETFORD" if regdist=="EAST RETFORD"
replace district="EAST STONEHOUSE" if regdist=="EAST STONEHOUSE"
replace district="EAST WARD" if regdist=="EAST WARD"
replace district="EASTBOURNE" if regdist=="EASTBOURNE"
replace district="EASTHAMPSTEAD" if regdist=="EASTHAMPSTEAD"
replace district="EASTRY" if regdist=="EASTRY"
replace district="ECCLESALL BIERLOW" if regdist=="ECCLESALL BIERLOW"
replace district="BARNET AND EDMONTON" if regdist=="EDMONTON"
replace district="ELHAM" if regdist=="ELHAM"
replace district="CHESTER ETC" if regdist=="ELLESMERE"
replace district="ELY" if regdist=="ELY"
replace district="EPPING" if regdist=="EPPING"
replace district="EPSOM AND REIGATE" if regdist=="EPSOM"
replace district="ERPINGHAM ETC" if regdist=="ERPINGHAM"
replace district="AMERSHAM AND ETON" if regdist=="ETON"
replace district="EVESHAM" if regdist=="EVESHAM"
replace district="EXETER AND ST THOMAS" if regdist=="EXETER"
replace district="FALMOUTH" if regdist=="FALMOUTH"
replace district="FAREHAM" if regdist=="FAREHAM"
replace district="FARINGDON" if regdist=="FARINGDON"
replace district="FARNHAM" if regdist=="FARNBOROUGH"
replace district="FARNHAM" if regdist=="FARNHAM"
replace district="FAVERSHAM" if regdist=="FAVERSHAM"
replace district="FESTINIOG" if regdist=="FESTINIOG"
replace district="COVENTRY ETC" if regdist=="FOLESHILL"
replace district="FORDINGBRIDGE" if regdist=="FORDINGBRIDGE"
replace district="FOREHOE" if regdist=="FOREHOE"
replace district="KINGS LYNN" if regdist=="FREEBRIDGE LYNN"
replace district="BATH ETC" if regdist=="FROME"
replace district="FYLDE" if regdist=="FYLDE"
replace district="GAINSBOROUGH" if regdist=="GAINSBOROUGH"
replace district="GARSTANG" if regdist=="GARSTANG"
replace district="GATESHEAD" if regdist=="GATESHEAD"
replace district="GLANFORD BRIGG" if regdist=="GLANFORD BRIGG"
replace district="GLENDALE" if regdist=="GLENDALE"
replace district="GLOUCESTER" if regdist=="GLOUCESTER"
replace district="CHICHESTER ETC" if regdist=="GODSTONE"
replace district="GOOLE" if regdist=="GOOLE"
replace district="GRANTHAM" if regdist=="GRANTHAM"
replace district="GRAVESEND" if regdist=="GRAVESEND AND MILTON"
replace district="CHESTER ETC" if regdist=="GREAT BOUGHTON"
replace district="GREENWICH" if regdist=="GREENWICH"
replace district="FARNHAM" if regdist=="GUILDFORD"
replace district="GUILTCROSS" if regdist=="GUILTCROSS"
replace district="HELMSLEY ETC" if regdist=="GUISBOROUGH"
replace district="HACKNEY" if regdist=="HACKNEY"
replace district="HAILSHAM AND LEWES" if regdist=="HAILSHAM"
replace district="HALIFAX" if regdist=="HALIFAX"
replace district="HALSTEAD" if regdist=="HALSTEAD"
replace district="HALTWHISTLE" if regdist=="HALTWHISTLE"
replace district="FARNHAM" if regdist=="HAMBLEDON"
replace district="HAMPSTEAD" if regdist=="HAMPSTEAD"
replace district="HARDINGSTONE" if regdist=="HARDINGSTONE"
replace district="HARTISMERE" if regdist=="HARTISMERE"
replace district="FARNHAM" if regdist=="HARTLEY WINTNEY"
replace district="HASLINGDEN" if regdist=="HASLINGDEN"
replace district="HASTINGS" if regdist=="HASTINGS"
replace district="HATFIELD" if regdist=="HATFIELD"
replace district="HAVANT" if regdist=="HAVANT"
replace district="HAVERFORDWEST" if regdist=="HAVERFORDWEST"
replace district="HAY" if regdist=="HAY"
replace district="HAYFIELD" if regdist=="HAYFIELD"
replace district="OXFORD" if regdist=="HEADINGTON"
replace district="HELMSLEY ETC" if regdist=="HELMSLEY"
replace district="HELSTON" if regdist=="HELSTON"
replace district="HEMEL HEMPSTEAD AND LUTON" if regdist=="HEMEL HEMPSTEAD"
replace district="PONTEFRACT HEMSWORTH" if regdist=="HEMSWORTH"
replace district="HENDON" if regdist=="HENDON"
replace district="READING" if regdist=="HENLEY"
replace district="HENSTEAD" if regdist=="HENSTEAD"
replace district="HEREFORD" if regdist=="HEREFORD"
replace district="HERTFORD" if regdist=="HERTFORD"
replace district="DURHAM" if regdist=="HEXHAM"
replace district="HIGHWORTH" if regdist=="HIGHWORTH AND SWINDON"
replace district="COVENTRY ETC" if regdist=="HINCKLEY"
replace district="HITCHIN" if regdist=="HITCHIN"
replace district="HOLBEACH" if regdist=="HOLBEACH"
replace district="HOLBORN" if regdist=="HOLBORN"
replace district="HOLLINGBOURN" if regdist=="HOLLINGBOURNE"
replace district="BIDEFORD ETC" if regdist=="HOLSWORTHY"
replace district="HOLYWELL" if regdist=="HOLYWELL"
replace district="BEAMINSTER ETC" if regdist=="HONITON"
replace district="HOO" if regdist=="HOO"
replace district="BOSTON ETC" if regdist=="HORNCASTLE"
replace district="CHICHESTER ETC" if regdist=="HORSHAM"
replace district="DURHAM" if regdist=="HOUGHTON LE SPRING"
replace district="HOWDEN" if regdist=="HOWDEN"
replace district="HOXNE AND DEPWADE" if regdist=="HOXNE"
replace district="HUDDERSFIELD" if regdist=="HUDDERSFIELD"
replace district="HULL" if regdist=="HULL"
replace district="HUNGERFORD" if regdist=="HUNGERFORD"
replace district="GREATER LEEDS" if regdist=="HUNSLET"
replace district="HUNTINGDON" if regdist=="HUNTINGDON"
replace district="IPSWICH" if regdist=="IPSWICH"
replace district="ISLE OF WIGHT" if regdist=="ISLE OF WIGHT"
replace district="SCILLY ISLES" if regdist=="ISLES OF SCILLY"
replace district="ISLINGTON" if regdist=="ISLINGTON"
replace district="SKIPTON AND KEIGHLEY" if regdist=="KEIGHLEY"
replace district="KENDAL" if regdist=="KENDAL"
replace district="KENSINGTON" if regdist=="KENSINGTON"
replace district="KETTERING AND OUNDLE" if regdist=="KETTERING"
replace district="BRISTOL" if regdist=="KEYNSHAM"
replace district="CLEOBURY-MORTIMER AND KIDDERMINSTER" if regdist=="KIDDERMINSTER"
replace district="KINGS LYNN" if regdist=="KINGS LYNN"
replace district="KINGS NORTON" if regdist=="KINGS NORTON"
replace district="KINGSBRIDGE" if regdist=="KINGSBRIDGE"
replace district="KINGSCLERE AND NEWBURY" if regdist=="KINGSCLERE"
replace district="KINGSTON" if regdist=="KINGSTON"
replace district="GREATER LEEDS" if regdist=="KNARESBOROUGH"
replace district="KNIGHTON" if regdist=="KNIGHTON"
replace district="LAMBETH" if regdist=="LAMBETH"
replace district="LAMPETER" if regdist=="LAMPETER"
replace district="LANCASTER" if regdist=="LANCASTER"
replace district="LANGPORT" if regdist=="LANGPORT"
replace district="BIDEFORD ETC" if regdist=="LAUNCESTON"
replace district="WORCESTER ETC" if regdist=="LEDBURY"
replace district="GREATER LEEDS" if regdist=="LEEDS"
replace district="WOLSTANTON ETC" if regdist=="LEEK"
replace district="LEICESTER" if regdist=="LEICESTER"
replace district="LEIGH" if regdist=="LEIGH"
replace district="BERKHAMPSTEAD" if regdist=="LEIGHTON BUZZARD"
replace district="LEOMINSTER" if regdist=="LEOMINSTER"
replace district="HAILSHAM AND LEWES" if regdist=="LEWES"
replace district="GREENWICH" if regdist=="LEWISHAM"
replace district="MALDON ETC" if regdist=="LEXDEN AND WINSTREE"
replace district="GREATER LEEDS" if regdist=="LEYBURN"
replace district="LICHFIELD" if regdist=="LICHFIELD"
replace district="LINCOLN" if regdist=="LINCOLN"
replace district="LINTON" if regdist=="LINTON"
replace district="TAVISTOCK AND LISKEARD" if regdist=="LISKEARD"
replace district="LIVERPOOL" if regdist=="LIVERPOOL"
replace district="LLANDOVERY ETC" if regdist=="LLANDILO FAWR"
replace district="LLANDOVERY ETC" if regdist=="LLANDOVERY"
replace district="LLANELLY AND CARMARTHEN" if regdist=="LLANELLY"
replace district="MONTGOMERY AND LLANFYLLIN" if regdist=="LLANFYLLIN"
replace district="LLANRWST" if regdist=="LLANRWST"
replace district="LODDON" if regdist=="LODDON AND CLAVERING"
replace district="" if regdist=="LONGTOWN"
replace district="LOUGHBOROUGH" if regdist=="LOUGHBOROUGH"
replace district="LOUTH" if regdist=="LOUTH"
replace district="LUDLOW" if regdist=="LUDLOW"
replace district="HEMEL HEMPSTEAD AND LUTON" if regdist=="LUTON"
replace district="LUTTERWORTH ETC" if regdist=="LUTTERWORTH"
replace district="CHRISTCHURCH" if regdist=="LYMINGTON"
replace district="MACCLESFIELD" if regdist=="MACCLESFIELD"
replace district="MACHYNLLETH" if regdist=="MACHYNLLETH"
replace district="MADELEY" if regdist=="MADELEY"
replace district="MAIDSTONE" if regdist=="MAIDSTONE"
replace district="MALDON ETC" if regdist=="MALDON"
replace district="MALLING" if regdist=="MALLING"
replace district="MALMSBURY" if regdist=="MALMESBURY"
replace district="MALTON" if regdist=="MALTON"
replace district="GREATER MANCHESTER" if regdist=="MANCHESTER"
replace district="MANSFIELD" if regdist=="MANSFIELD"
replace district="MARKET BOSWORTH" if regdist=="MARKET BOSWORTH"
replace district="MARKET DRAYTON" if regdist=="MARKET DRAYTON"
replace district="LUTTERWORTH ETC" if regdist=="MARKET HARBOROUGH"
replace district="CRICKLADE ETC" if regdist=="MARLBOROUGH"
replace district="WORCESTER ETC" if regdist=="MARTLEY"
replace district="MARYLEBONE" if regdist=="MARYLEBONE"
replace district="MEDWAY" if regdist=="MEDWAY"
replace district="MELKSHAM" if regdist=="MELKSHAM"
replace district="MELTON MOWBRAY" if regdist=="MELTON MOWBRAY"
replace district="SHAFTESBURY ETC" if regdist=="MERE"
replace district="MERIDEN AND SOLIHULL" if regdist=="MERIDEN"
replace district="CARDIFF AND NEWPORT" if regdist=="MERTHYR TIDVIL"
replace district="CHICHESTER ETC" if regdist=="MIDHURST"
replace district="MILDENHALL" if regdist=="MILDENHALL"
replace district="MILTON" if regdist=="MILTON"
replace district="MITFORD" if regdist=="MITFORD AND LAUNDITCH"
replace district="MONMOUTH" if regdist=="MONMOUTH"
replace district="MONTGOMERY AND LLANFYLLIN" if regdist=="MONTGOMERY"
replace district="MORPETH" if regdist=="MORPETH"
replace district="MUTFORD AND YARMOUTH" if regdist=="MUTFORD AND LOTHINGLAND"
replace district="CHESTER ETC" if regdist=="NANTWICH"
replace district="NARBERTH" if regdist=="NARBERTH"
replace district="SWANSEA ETC" if regdist=="NEATH"
replace district="NEW FOREST" if regdist=="NEW FOREST"
replace district="NEWARK" if regdist=="NEWARK"
replace district="KINGSCLERE AND NEWBURY" if regdist=="NEWBURY"
replace district="NEWCASTLE-IN-EMLYN" if regdist=="NEWCASTLE IN EMLYN"
replace district="STOKE ETC" if regdist=="NEWCASTLE UNDER LYME"
replace district="NEWCASTLE-UPON-TYNE" if regdist=="NEWCASTLE UPON TYNE"
replace district="WESTBURY-ON-SEVERN ETC" if regdist=="NEWENT"
replace district="ST SAVIOUR SOUTHWARK" if regdist=="NEWINGTON ST MARY"
replace district="NEWMARKET" if regdist=="NEWMARKET"
replace district="NEWPORT PAGNELL" if regdist=="NEWPORT PAGNELL"
replace district="NEWTON ABBOT" if regdist=="NEWTON ABBOT"
replace district="NEWTOWN" if regdist=="NEWTOWN AND LLANIDLOES"
replace district="NORTH AYLESFORD" if regdist=="NORTH AYLESFORD"
replace district="NORTH WITCHFORD" if regdist=="NORTH WITCHFORD"
replace district="NORTHALLERTON" if regdist=="NORTHALLERTON"
replace district="NORTHAMPTON" if regdist=="NORTHAMPTON"
replace district="NORTHLEACH" if regdist=="NORTHLEACH"
replace district="WOLSTANTON ETC" if regdist=="NORTHWICH"
replace district="NORWICH AND ST FAITHS" if regdist=="NORWICH"
replace district="NOTTINGHAM ETC" if regdist=="NOTTINGHAM"
replace district="COVENTRY ETC" if regdist=="NUNEATON"
replace district="OAKHAM" if regdist=="OAKHAM"
replace district="OKEHAMPTON" if regdist=="OKEHAMPTON"
replace district="OLDHAM" if regdist=="OLDHAM"
replace district="ONGAR" if regdist=="ONGAR"
replace district="ORMSKIRK" if regdist=="ORMSKIRK"
replace district="ORSETT" if regdist=="ORSETT"
replace district="OSWESTRY" if regdist=="OSWESTRY"
replace district="GREATER LEEDS" if regdist=="OTLEY"
replace district="KETTERING AND OUNDLE" if regdist=="OUNDLE"
replace district="OXFORD" if regdist=="OXFORD"
replace district="PANCRAS" if regdist=="PANCRAS"
replace district="GREATER LEEDS" if regdist=="PATELEY BRIDGE"
replace district="PATRINGTON" if regdist=="PATRINGTON"
replace district="PEMBROKE" if regdist=="PEMBROKE"
replace district="CANNOCK" if regdist=="PENKRIDGE"
replace district="PENRITH" if regdist=="PENRITH"
replace district="PENZANCE" if regdist=="PENZANCE"
replace district="PERSHORE" if regdist=="PERSHORE"
replace district="PETERBOROUGH" if regdist=="PETERBOROUGH"
replace district="FARNHAM" if regdist=="PETERSFIELD"
replace district="CHICHESTER ETC" if regdist=="PETWORTH"
replace district="ANDOVER" if regdist=="PEWSEY"
replace district="PICKERING" if regdist=="PICKERING"
replace district="PLOMESGATE" if regdist=="PLOMESGATE"
replace district="PLYMOUTH" if regdist=="PLYMOUTH"
replace district="PLYMOUTH" if regdist=="PLYMPTON ST MARY"
replace district="POCKLINGTON" if regdist=="POCKLINGTON"
replace district="ABERGAVENNY AND PONTYPOOL" if regdist=="PONT Y POOL"
replace district="PONTEFRACT HEMSWORTH" if regdist=="PONTEFRACT"
replace district="POOLE" if regdist=="POOLE"
replace district="POPLAR" if regdist=="POPLAR"
replace district="PORTSMOUTH" if regdist=="PORTSEA ISLAND"
replace district="POTTERSPURY" if regdist=="POTTERSPURY"
replace district="PRESCOT" if regdist=="PRESCOT"
replace district="KINGTON" if regdist=="PRESTEIGNE"
replace district="PRESTON" if regdist=="PRESTON"
replace district="PWLLHELI" if regdist=="PWLLHELI"
replace district="NOTTINGHAM ETC" if regdist=="RADFORD"
replace district="READING" if regdist=="READING"
replace district="REDRUTH" if regdist=="REDRUTH"
replace district="REETH" if regdist=="REETH"
replace district="EPSOM AND REIGATE" if regdist=="REIGATE"
replace district="RHAYADER" if regdist=="RHAYADER"
replace district="" if regdist=="RICHMOND"
replace district="" if regdist=="RICHMOND"
replace district="RINGWOOD" if regdist=="RINGWOOD"
replace district="GREATER LEEDS" if regdist=="RIPON"
replace district="RISBRIDGE" if regdist=="RISBRIDGE"
replace district="ROCHDALE" if regdist=="ROCHDALE"
replace district="BILLERICAY AND ROCHFORD" if regdist=="ROCHFORD"
replace district="ROMFORD" if regdist=="ROMFORD"
replace district="ROMNEY MARSH" if regdist=="ROMNEY MARSH"
replace district="ROMSEY" if regdist=="ROMSEY"
replace district="WESTBURY-ON-SEVERN ETC" if regdist=="ROSS"
replace district="ROTHBURY" if regdist=="ROTHBURY"
replace district="CHESTERFIELD" if regdist=="ROTHERHAM"
replace district="ST OLAVE SOUTHWARK" if regdist=="ROTHERHITHE"
replace district="ROYSTON" if regdist=="ROYSTON"
replace district="RUGBY" if regdist=="RUGBY"
replace district="RUNCORN AND WARRINGTON" if regdist=="RUNCORN"
replace district="RUTHIN" if regdist=="RUTHIN"
replace district="RYE" if regdist=="RYE"
replace district="SADDLEWORTH" if regdist=="SADDLEWORTH"
replace district="SAFFRON WALDON" if regdist=="SAFFRON WALDEN"
replace district="GREATER MANCHESTER" if regdist=="SALFORD"
replace district="SALISBURY" if regdist=="SALISBURY"
replace district="SAMFORD" if regdist=="SAMFORD"
replace district="SCARBOROUGH" if regdist=="SCARBOROUGH"
replace district="SCULCOATES" if regdist=="SCULCOATES"
replace district="SEDBERGH" if regdist=="SEDBERGH"
replace district="YORK" if regdist=="SELBY"
replace district="SETTLE" if regdist=="SETTLE"
replace district="SEVENOAKS" if regdist=="SEVENOAKS"
replace district="SHAFTESBURY ETC" if regdist=="SHAFTESBURY"
replace district="DERBY ETC" if regdist=="SHARDLOW"
replace district="SHEFFIELD" if regdist=="SHEFFIELD"
replace district="SHEPPEY" if regdist=="SHEPPEY"
replace district="BRIDGEWATER ETC" if regdist=="SHEPTON MALLET"
replace district="SHERBORNE AND YEOVIL" if regdist=="SHERBORNE"
replace district="SHIFFNAL" if regdist=="SHIFNAL"
replace district="SHIPSTON-ON-STOUR" if regdist=="SHIPSTON ON STOUR"
replace district="SHOREDITCH" if regdist=="SHOREDITCH"
replace district="ATCHAM AND SHREWSBURY" if regdist=="SHREWSBURY"
replace district="SKIPTON AND KEIGHLEY" if regdist=="SKIPTON"
replace district="SKIRLAUGH" if regdist=="SKIRLAUGH"
replace district="BOSTON ETC" if regdist=="SLEAFORD"
replace district="MERIDEN AND SOLIHULL" if regdist=="SOLIHULL"
replace district="TIVERTON ETC" if regdist=="SOUTH MOLTON"
replace district="SOUTH SHIELDS" if regdist=="SOUTH SHIELDS"
replace district="WINCHESTER" if regdist=="SOUTH STONEHAM"
replace district="SOUTHAM" if regdist=="SOUTHAM"
replace district="SOUTHAMPTON" if regdist=="SOUTHAMPTON"
replace district="ST SAVIOUR SOUTHWARK" if regdist=="SOUTHWARK ST GEORGE THE MARTYR"
replace district="SOUTHWELL" if regdist=="SOUTHWELL"
replace district="BOURN AND SPALDING" if regdist=="SPALDING"
replace district="BOSTON ETC" if regdist=="SPILSBY"
replace district="ST ALBANS" if regdist=="ST ALBANS"
replace district="ST ASAPH" if regdist=="ST ASAPH"
replace district="ST AUSTELL" if regdist=="ST AUSTELL"
replace district="BODMIN AND ST COLUMB" if regdist=="ST COLUMB MAJOR"
replace district="NORWICH AND ST FAITHS" if regdist=="ST FAITHS"
replace district="ST GEORGE IN THE EAST" if regdist=="ST GEORGE IN THE EAST"
replace district="WESTMINSTER" if regdist=="ST GEORGES"
replace district="ST GERMANS" if regdist=="ST GERMANS"
replace district="ST GILES" if regdist=="ST GILES IN THE FIELDS AND ST GEORGE BLOOMSBURY"
replace district="ST IVES" if regdist=="ST IVES"
replace district="WESTMINSTER" if regdist=="ST JAMES"
replace district="HOLBORN" if regdist=="ST LUKE"
replace district="WESTMINSTER" if regdist=="ST MARGARET AND ST JOHN"
replace district="WESTMINSTER" if regdist=="ST MARTIN IN THE FIELDS"
replace district="ST NEOTS" if regdist=="ST NEOTS"
replace district="ST OLAVE SOUTHWARK" if regdist=="ST OLAVE SOUTHWARK"
replace district="ST SAVIOUR SOUTHWARK" if regdist=="ST SAVIOURS"
replace district="EXETER AND ST THOMAS" if regdist=="ST THOMAS"
replace district="STAFFORD" if regdist=="STAFFORD"
replace district="STAINES" if regdist=="STAINES"
replace district="STAMFORD" if regdist=="STAMFORD"
replace district="STEPNEY and MILE END" if regdist=="STEPNEY"
replace district="THAKEHAM" if regdist=="STEYNING"
replace district="SALISBURY" if regdist=="STOCKBRIDGE"
replace district="STOCKPORT" if regdist=="STOCKPORT"
replace district="HELMSLEY ETC" if regdist=="STOCKTON"
replace district="PLYMOUTH" if regdist=="STOKE DAMEREL"
replace district="STOKE ETC" if regdist=="STOKE ON TRENT"
replace district="HELMSLEY ETC" if regdist=="STOKESLEY"
replace district="STOKE ETC" if regdist=="STONE"
replace district="WEST BROMWICH AND STOURBRIDGE" if regdist=="STOURBRIDGE"
replace district="STOW" if regdist=="STOW"
replace district="STOW-ON-THE-WOLD" if regdist=="STOW ON THE WOLD"
replace district="WESTMINSTER" if regdist=="STRAND"
replace district="STRATFORD-ON-AVON" if regdist=="STRATFORD ON AVON"
replace district="STRATTON" if regdist=="STRATTON"
replace district="STROUD AND TETBURY" if regdist=="STROUD"
replace district="STURMINSTER" if regdist=="STURMINSTER"
replace district="SUDBURY" if regdist=="SUDBURY"
replace district="SUNDERLAND" if regdist=="SUNDERLAND"
replace district="SWAFFHAM" if regdist=="SWAFFHAM"
replace district="SWANSEA ETC" if regdist=="SWANSEA"
replace district="YORK" if regdist=="TADCASTER"
replace district="TAMWORTH" if regdist=="TAMWORTH"
replace district="TAUNTON" if regdist=="TAUNTON"
replace district="TAVISTOCK AND LISKEARD" if regdist=="TAVISTOCK"
replace district="TEESDALE" if regdist=="TEESDALE"
replace district="TENBURY" if regdist=="TENBURY"
replace district="MALDON ETC" if regdist=="TENDRING"
replace district="TENTERDEN" if regdist=="TENTERDEN"
replace district="STROUD AND TETBURY" if regdist=="TETBURY"
replace district="TEWKESBURY" if regdist=="TEWKESBURY"
replace district="THAKEHAM" if regdist=="THAKENHAM"
replace district="WYCOMBE AYLESBURY THAME" if regdist=="THAME"
replace district="THANET" if regdist=="THANET"
replace district="THETFORD" if regdist=="THETFORD"
replace district="THINGOE" if regdist=="THINGOE"
replace district="GREATER LEEDS" if regdist=="THIRSK"
replace district="THORNBURY" if regdist=="THORNBURY"
replace district="THORNE" if regdist=="THORNE"
replace district="THRAPSTON" if regdist=="THRAPSTON"
replace district="TICEHURST" if regdist=="TICEHURST"
replace district="TISBURY" if regdist=="TISBURY"
replace district="TIVERTON ETC" if regdist=="TIVERTON"
replace district="BRADFORD ETC" if regdist=="TODMORDEN"
replace district="TONBRIDGE" if regdist=="TONBRIDGE"
replace district="TORRINGTON" if regdist=="TORRINGTON"
replace district="TOTNES" if regdist=="TOTNES"
replace district="TOWCESTER" if regdist=="TOWCESTER"
replace district="TREGARON" if regdist=="TREGARON"
replace district="TRURO" if regdist=="TRURO"
replace district="ERPINGHAM ETC" if regdist=="TUNSTEAD AND HAPPING"
replace district="TYNEMOUTH" if regdist=="TYNEMOUTH"
replace district="UCKFIELD" if regdist=="UCKFIELD"
replace district="ULVERSTONE AND BARROW-IN-FURNESS" if regdist=="ULVERSTON"
replace district="LUTTERWORTH ETC" if regdist=="UPPINGHAM"
replace district="WORCESTER ETC" if regdist=="UPTON UPON SEVERN"
replace district="STOKE ETC" if regdist=="UTTOXETER"
replace district="UXBRIDGE AND BRENTFORD" if regdist=="UXBRIDGE"
replace district="WAKEFIELD" if regdist=="WAKEFIELD"
replace district="WALLINGFORD" if regdist=="WALLINGFORD"
replace district="WALSALL" if regdist=="WALSALL"
replace district="ERPINGHAM ETC" if regdist=="WALSINGHAM"
replace district="WANDSWORTH" if regdist=="WANDSWORTH"
replace district="WANGFORD" if regdist=="WANGFORD"
replace district="WANTAGE" if regdist=="WANTAGE"
replace district="WARE" if regdist=="WARE"
replace district="WAREHAM" if regdist=="WAREHAM AND PURBECK"
replace district="WARMINSTER" if regdist=="WARMINSTER"
replace district="RUNCORN AND WARRINGTON" if regdist=="WARRINGTON"
replace district="WARWICK" if regdist=="WARWICK"
replace district="WATFORD" if regdist=="WATFORD"
replace district="WAYLAND" if regdist=="WAYLAND"
replace district="WEARDALE" if regdist=="WEARDALE"
replace district="WELLINGBOROUGH" if regdist=="WELLINGBOROUGH"
replace district="" if regdist=="WELLINGTON"
replace district="" if regdist=="WELLINGTON"
replace district="BRIDGEWATER ETC" if regdist=="WELLS"
replace district="CHESTER ETC" if regdist=="WEM"
replace district="WEOBLY" if regdist=="WEOBLEY"
replace district="WEST ASHFORD" if regdist=="WEST ASHFORD"
replace district="WEST BROMWICH AND STOURBRIDGE" if regdist=="WEST BROMWICH"
replace district="WEST DERBY" if regdist=="WEST DERBY"
replace district="WEST HAM" if regdist=="WEST HAM"
replace district="LONDON CITY" if regdist=="WEST LONDON"
replace district="WEST WARD" if regdist=="WEST WARD"
replace district="WESTBOURNE" if regdist=="WESTBOURNE"
replace district="WESTBURY" if regdist=="WESTBURY AND WHORWELLSDOWN"
replace district="WESTBURY-ON-SEVERN ETC" if regdist=="WESTBURY ON SEVERN"
replace district="CHICHESTER ETC" if regdist=="WESTHAMPNETT"
replace district="WEYMOUTH" if regdist=="WEYMOUTH"
replace district="WHEATENHURST" if regdist=="WHEATENHURST"
replace district="WHITBY" if regdist=="WHITBY"
replace district="" if regdist=="WHITCHURCH"
replace district="WHITECHAPEL" if regdist=="WHITECHAPEL"
replace district="WHITEHAVEN" if regdist=="WHITEHAVEN"
replace district="WHITTLESEY" if regdist=="WHITTLESEY"
replace district="WIGAN" if regdist=="WIGAN"
replace district="WIGTON" if regdist=="WIGTON"
replace district="WILLITON" if regdist=="WILLITON"
replace district="WILTON" if regdist=="WILTON"
replace district="BLANDFORD AND WIMBORNE" if regdist=="WIMBORNE"
replace district="SHAFTESBURY ETC" if regdist=="WINCANTON"
replace district="WINCHCOMB" if regdist=="WINCHCOMBE"
replace district="WINCHESTER" if regdist=="WINCHESTER"
replace district="WINDSOR" if regdist=="WINDSOR"
replace district="WINSLOW" if regdist=="WINSLOW"
replace district="WIRRALL AND BIRKENHEAD" if regdist=="WIRRAL"
replace district="WISBEACH" if regdist=="WISBECH"
replace district="MALDON ETC" if regdist=="WITHAM"
replace district="WITNEY" if regdist=="WITNEY"
replace district="BERKHAMPSTEAD" if regdist=="WOBURN"
replace district="READING" if regdist=="WOKINGHAM"
replace district="WOLSTANTON ETC" if regdist=="WOLSTANTON AND BURSLEM"
replace district="WOLVERHAMPTON" if regdist=="WOLVERHAMPTON"
replace district="IPSWICH" if regdist=="WOODBRIDGE"
replace district="WOODSTOCK" if regdist=="WOODSTOCK"
replace district="WORCESTER ETC" if regdist=="WORCESTER"
replace district="CHESTERFIELD" if regdist=="WORKSOP"
replace district="WORTLEY" if regdist=="WORTLEY"
replace district="CHESTER ETC" if regdist=="WREXHAM"
replace district="WYCOMBE AYLESBURY THAME" if regdist=="WYCOMBE"
replace district="MUTFORD AND YARMOUTH" if regdist=="YARMOUTH"
replace district="SHERBORNE AND YEOVIL" if regdist=="YEOVIL"
replace district="YORK" if regdist=="YORK"


replace district="CARDIFF AND NEWPORT" if regdist=="NEWPORT" & NATION=="WALES"
replace district="NEWPORT (SALOP)" if regdist=="NEWPORT" & NATION!="WALES"

drop if district=="" //Small number of districts that are ambiguously names shouldn't affect main takeawy of map.

keep id district
compress
save "$temp_dir/EW_dist_ids.dta", replace
